version: "3.7"

services:
  salt:
    env_file:
      - variables.env
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - AUDIOGUILD_DATABASE_DB=${AUDIOGUILD_DATABASE_DB}
        - AUDIOGUILD_DATABASE_URL=${AUDIOGUILD_DATABASE_URL}
        - AUDIOGUILD_POSTGRES_USER=${AUDIOGUILD_POSTGRES_USER}
        - AUDIOGUILD_POSTGRES_PW=${AUDIOGUILD_POSTGRES_PW}
        - SECRET_KEY=${SECRET_KEY}
        - MAIL_USERNAME=${MAIL_USERNAME}
        - MAIL_PASSWORD=${MAIL_PASSWORD}
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
        - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
    ports:
      - "6000:6000"
    environment: 
      - AUDIOGUILD_DATABASE_DB=${AUDIOGUILD_DATABASE_DB}
      - AUDIOGUILD_DATABASE_URL=${AUDIOGUILD_DATABASE_URL}
      - AUDIOGUILD_POSTGRES_USER=${AUDIOGUILD_POSTGRES_USER}
      - AUDIOGUILD_POSTGRES_PW=${AUDIOGUILD_POSTGRES_PW}
      - SECRET_KEY=${SECRET_KEY}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}