version: "3.7"

services:
  salt:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment: 
      - FLASK_ENV=development
      - FLASK_APP=run.py
      - FLASK_DEBUG=1