FROM python:3.8-slim

RUN apt-get update
RUN apt-get install -y postgresql libpq-dev postgresql-client postgresql-client-common gcc

ENV FLASK_ENV=production

ARG AUDIOGUILD_DATABASE_DB 
ARG AUDIOGUILD_DATABASE_URL 
ARG AUDIOGUILD_POSTGRES_USER 
ARG AUDIOGUILD_POSTGRES_PW
ARG SECRET_KEY 
ARG MAIL_USERNAME 
ARG MAIL_PASSWORD 
ARG AWS_ACCESS_KEY_ID 
ARG AWS_SECRET_ACCESS_KEY
ARG STRIPE_SECRET_KEY
ARG STRIPE_PUBLISHABLE_KEY

ENV AUDIOGUILD_DATABASE_DB ${AUDIOGUILD_DATABASE_DB}
ENV AUDIOGUILD_DATABASE_URL ${AUDIOGUILD_DATABASE_URL}
ENV AUDIOGUILD_POSTGRES_USER ${AUDIOGUILD_POSTGRES_USER}
ENV AUDIOGUILD_POSTGRES_PW ${AUDIOGUILD_POSTGRES_PW}
ENV SECRET_KEY ${SECRET_KEY}
ENV MAIL_USERNAME ${MAIL_USERNAME}
ENV MAIL_PASSWORD ${MAIL_PASSWORD}
ENV AWS_ACCESS_KEY_ID ${AWS_ACCESS_KEY_ID}
ENV AWS_SECRET_ACCESS_KEY ${AWS_SECRET_ACCESS_KEY}
ENV STRIPE_SECRET_KEY ${STRIPE_SECRET_KEY}
ENV STRIPE_PUBLISHABLE_KEY ${STRIPE_PUBLISHABLE_KEY}

WORKDIR /

ADD . .

RUN pip3 install -r requirements.txt

EXPOSE 443

CMD ["gunicorn", "-b", "0.0.0.0:6000", "run:app"]