"""empty message

Revision ID: 07098bd6b4a6
Revises: 814b385ce1b4
Create Date: 2021-12-21 17:57:39.171609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07098bd6b4a6'
down_revision = '814b385ce1b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track_asset', sa.Column('length', sa.Float(), nullable=True))
    op.add_column('track_asset', sa.Column('waveform', sa.ARRAY(sa.Float()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track_asset', 'waveform')
    op.drop_column('track_asset', 'length')
    # ### end Alembic commands ###
