"""empty message

Revision ID: 425bbdc83478
Revises: 0dcd2cd124e8
Create Date: 2021-06-30 10:27:08.299386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '425bbdc83478'
down_revision = '0dcd2cd124e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('coins', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'coins')
    # ### end Alembic commands ###
