"""empty message

Revision ID: 559ca127dba9
Revises: aa45adb662e9
Create Date: 2021-11-07 10:26:58.511357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '559ca127dba9'
down_revision = 'aa45adb662e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'active')
    # ### end Alembic commands ###
