"""empty message

Revision ID: 5960fe24cbca
Revises: 911a850ef87d
Create Date: 2021-12-22 21:01:39.841933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5960fe24cbca'
down_revision = '911a850ef87d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track_asset', sa.Column('author', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track_asset', 'author')
    # ### end Alembic commands ###
