"""empty message

Revision ID: 6645bea9d31d
Revises: 5960fe24cbca
Create Date: 2021-12-24 19:04:22.774693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6645bea9d31d'
down_revision = '5960fe24cbca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track_asset', sa.Column('author_id', sa.Integer(), nullable=True))
    op.add_column('track_asset', sa.Column('author_username', sa.String(length=40), nullable=True))
    op.add_column('track_asset', sa.Column('downloads', sa.Integer(), nullable=False))
    op.drop_column('track_asset', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track_asset', sa.Column('author', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.drop_column('track_asset', 'downloads')
    op.drop_column('track_asset', 'author_username')
    op.drop_column('track_asset', 'author_id')
    # ### end Alembic commands ###
