"""empty message

Revision ID: 814b385ce1b4
Revises: f77c9fd14639
Create Date: 2021-12-15 14:23:42.190013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '814b385ce1b4'
down_revision = 'f77c9fd14639'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('track_asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('audio_metadata', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('track_asset')
    # ### end Alembic commands ###
