"""pack active and false nulls

Revision ID: 846aa2f90e0c
Revises: a21b839db4d4
Create Date: 2021-06-30 12:20:32.446414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '846aa2f90e0c'
down_revision = 'a21b839db4d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entry', 'complete',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('pack', sa.Column('active', sa.Boolean(), nullable=False))
    op.alter_column('project', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('project', 'complete',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'complete',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('project', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('pack', 'active')
    op.alter_column('entry', 'complete',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
