"""empty message

Revision ID: a192195065c7
Revises: c92bcc57203b
Create Date: 2022-06-09 21:11:57.591044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a192195065c7'
down_revision = 'c92bcc57203b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone')
    op.drop_column('user', 'address')
    # ### end Alembic commands ###
