"""pack and assetType

Revision ID: a21b839db4d4
Revises: 425bbdc83478
Create Date: 2021-06-30 11:50:40.773733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a21b839db4d4'
down_revision = '425bbdc83478'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('image_file', sa.String(length=120), nullable=False),
    sa.Column('video_file', sa.String(length=120), nullable=False),
    sa.Column('downloads', sa.Integer(), nullable=False),
    sa.Column('coin_cost', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('pack_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pack_id'], ['pack.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asset_type')
    op.drop_table('pack')
    # ### end Alembic commands ###
