"""empty message

Revision ID: c8e993154640
Revises: 07098bd6b4a6
Create Date: 2021-12-21 18:10:58.024347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8e993154640'
down_revision = '07098bd6b4a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track_asset', sa.Column('metadata', sa.ARRAY(sa.Float()), nullable=True))
    op.drop_column('track_asset', 'audio_metadata')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track_asset', sa.Column('audio_metadata', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('track_asset', 'metadata')
    # ### end Alembic commands ###
