"""empty message

Revision ID: c92bcc57203b
Revises: c6f29975cf35
Create Date: 2022-03-17 23:45:02.169062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c92bcc57203b'
down_revision = 'c6f29975cf35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('contributor', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'contributor')
    # ### end Alembic commands ###
