"""empty message

Revision ID: f09fb367b65a
Revises: 00fd95caf146
Create Date: 2022-01-21 18:17:28.692939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f09fb367b65a'
down_revision = '00fd95caf146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('premium', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('upload_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'upload_count')
    op.drop_column('user', 'premium')
    # ### end Alembic commands ###
