"""empty message

Revision ID: f77c9fd14639
Revises: 74a1aa5db0bb
Create Date: 2021-12-03 15:31:50.238699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f77c9fd14639'
down_revision = '74a1aa5db0bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset_type', 'status')
    op.add_column('contributed_asset', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contributed_asset', 'status')
    op.add_column('asset_type', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
