"""empty message

Revision ID: fd8f062e75e9
Revises: a192195065c7
Create Date: 2022-08-04 14:30:33.515946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd8f062e75e9'
down_revision = 'a192195065c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'track_asset', 'user', ['author_id'], ['id'])
    op.drop_column('track_asset', 'author_username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track_asset', sa.Column('author_username', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'track_asset', type_='foreignkey')
    # ### end Alembic commands ###
